### ISSUE TITLE
Standard library tracking issue (core)

### ISSUE THREAD

**Issue by WillBAnders** [Rhovas/Interpreter#2]
This is a tracking issue for progress on implementing the core of the standard library. The classes/functions in the core are roughly defined by either being language primitives (`Integer`, `List`, `Lambda`, `Comparable`, `Nullable`, etc; which are all directly used during semantic analysis) or key libraries/functions (`Set`, `File`, `print`, `sin`/`cos`/`tan`, etc; which are commonly used within algorithms). These two categories should allow Rhovas to be usable for basic leetcode and rosetta code problems, which is a fair starting point for testing the language.

## Language Primitives

 - [X] `Any`
 - [X] `Void`
 - [x] Literals:
    - [X] `Boolean`
    - [X] `Integer`, `Decimal`
    - [x] `String`,
    - [X] `Atom`
    - [x] <s>`Array`</s>, `List`
    - [x] `Map`, ~~`Object`~~, `Struct`
 - [x] `Lambda` (or `Func`?)
 - [x] `Exception` (or `Error`?)
 - [x] `Result`/`Nullable`
 - [x] Interfaces:
    - [x] `Equatable`, `Comparable`, `Hashable`
    - [x] `Iterable`, ~~`Collection`~~, ~~`Sequence`~~ (Hierarchy TBD)

## Key Libraries

Largely based on those present in `java.lang`/`java.util` and commonly used for leetcode and/or command line applications.

 - [x] `Kernel`:
    - [x] `input`, `print` (dedicated `Console` class?)
    - [X] `range`
    - [x] `lambda`
 - [x] `Math`
    - [X] `random` 
    - [X] `sqrt`
    - [X] `pow`, `log`
    - [X] `sin`, `cos`, `tan`
 - [x] `Regex`
 - [x] ~~`Date`~~, ~~`Time`~~ (JVM only)
 - [x] ~~`File`~~ (JVM only)
 - [x] Data Structures:
    - [x] `Set`
    - [x] ~~`Deque`~~, ~~`Stack`~~, ~~`Queue`~~ (Helpful but not core)
    - [x] ~~`Tree`~~ (?)

**Comment by WillBAnders** [comment]
Considering this completed. Items that were crossed off as 'won't do' are marked with notes in the description, mainly due to questions on abstractions or lack of JavaScript support.

I think moving forward, we should rely more heavily on Kotlin's standard library rather than try to redesign any APIs here - this helps immensely for documentation as well. I've made previous attempts at using reflection for this (quickly breaks down with extension functions and Kotlin/JS), but in thinking about this recently it may be feasible through code generation.
